### ISSUE TITLE
Absolutne poti, SQL injection, .gitignore

### ISSUE THREAD

**Issue by jaanos** [CusinM15/baza-Ekol#1]
Opažam, da se na datoteke sklicujeta z absolutnimi potmi, npr.
https://github.com/CusinM15/baza-Ekol/blob/ff078666a52c9f72eadc0e13686f92cc1e75d973/branje_excel.py#L6
Na ta način si zagotovita, da bo koda delovala na natanko enem računalniku. Namesto tega se na datoteke sklicujta glede na vrhnjo mapo repozitorija - glede na to, da je datoteka kar na vrhu, lahko torej naredita
```python
pot1 = r"ND_00_Seznam klasifikacij po dovoljenjih.xlsx"
```

Kot sem omenil na vajah, za vstavljanje podatkov ne uporabljajta metode `format`, pač pa podatke podajta v seznamu ali slovarju v drugem parametru metode `execute`. Na ta način se izogneta napadom [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/). Tako namesto
https://github.com/CusinM15/baza-Ekol/blob/ff078666a52c9f72eadc0e13686f92cc1e75d973/branje_excel.py#L118-L127
raje naredita nekaj takega:
```python
stolpci = ['pov', 'dat_uv', 'op_uv', 'dat_iz', 'op_iz', 'skl']
for (kl, teza), slo in sez_podatkov.items(): 
    sql = ''' 
        INSERT INTO odpadek  
        (teza, klasifikacijska_stevilka, povzrocitelj, prejemnik, datum_uvoza, opomba_uvoz, datum_izvoza, opomba_izvoz, skladisce )  
        VALUES  
        (?, ?, ?, ?, ?, ?, ?, ?, ?); 
        '''
    kazalec.execute(sql, [teza, kl, *(slo.get(s, '') for s in stolpci)])
```

Nazadnje, baze naj ne bo na repozitoriju (lahko si pomagata s kodo z [vzorčnega repozitorija](https://github.com/jaanos/podatkovne-baze-1), da se ustvari ob zagonu aplikacije) - pobrišita torej datoteko `Ekol.sqlite` in dodajta ustrezno vrstico v `.gitignore`, da je ne bosta po nesreči spet dodala.

**Comment by CusinM15** [comment]
Sva danes spremenila na relativno pot in z uporabo ?-ja. Kviza pa nisem
moral oddati, ker se mi je internet sesul, zato bi se opravičil.
lp Matej Čušin

V V pon., 14. dec. 2020 ob 11:41 je oseba Janoš Vidali <
notifications@github.com> napisala:

**Comment by jaanos** [comment]
V redu, če sta uredila, lahko tale issue zapreta.

@CusinM15, tvoj odgovor na kviz vidim, tako da tukaj ne bo problemov.

**Comment by CusinM15** [comment]
...
