### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by jaanos** [CusinM15/baza-Ekol#2]
Odgovarjam na e-pošto kar tukaj - če bosta imela kakšno vprašanje v prihodnje, bo najbolje, če kodo naložita na GitHub in odpreta issue, kjer se potem lahko na kodo [sklicujeta](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet), pa se lahko bolj natančno pogovarjamo.

Opažam, da na nekaj mestih definirata metodo `dodaj_vrstico`, ki samo kliče ustrezno metodo iz nadrazreda:
https://github.com/CusinM15/baza-Ekol/blob/fcb2b72af26714939cb6962e8ee6bfd64c60c300/poiskus.py#L93-L99
Tega vama ni potrebno početi - glede na to, da vajini razredi dedujejo od razreda `Tabela`, se bo ob klicu metode `dodaj_vrstico` uporabila kar metoda iz razreda `Tabela`, če je v samem razredu ne definirata še enkrat (v razredu `Podjetja` je seveda smiselno, da podasta novo definicijo).

Sicer pa parameter `**podatki` pomeni, da bo funkcija v spremenljivki `podatki` imela na voljo seznam poimenovanih parametrov. Trenutni način klicanja tako ni ustrezen:
https://github.com/CusinM15/baza-Ekol/blob/fcb2b72af26714939cb6962e8ee6bfd64c60c300/poiskus.py#L163-L166
Poleg tega, da podasta slovar kot parameter, metodo kličeta neposredno iz razreda namesto njegove instance. Svetoval bi, da kodo nekoliko preoblikujeta - za začetek naj `uvozi_podatke` kliče ustrezne metode na objektih, ki predstavljajo tabele:
```python
def uvozi_podatke(tabele, conn):
    """
    Uvozi podatke v podane tabele.
    """
    podjetja, vrsta_odpadka, skladisce, odpadek = tabele
    ... # trenutna koda funkcije
    with conn:
        vrsta_odpadka.uvozi(slo_klas_ste_ime)
        podjetja.uvozi(slo_id_podjetje)
        skladisce.uvozi(slo_sklad)
        odpadek.uvozi(sez_podatkov)
    conn.execute('VACUUM')
```
Namesto funkcije `napolni_tabele` potem definirajta metode `uvozi` v ustreznih razredih, npr.
```python
class VrstaOdpadka(Tabela):
    ...

    def uvozi(self, slo_klas_ste_ime):
        for kl, ime in slo_klas_ste_ime.items():
            self.dodaj_vrstico(klasifikacijska_stevilka=kl, naziv=ime)
```

Če bi podatke že imela spravljene v slovarju, potem ga lahko podasta kot parameter z zvezdicama, npr.
```python
class Skladisce(Tabela):
    ...

    def uvozi(self, slo_sklad):
        for ime, st in slo_sklad.items():
            nov = {'id': st, 'ime': ime} # tukaj ni potrebe po tem pristopu
            self.dodaj_vrstico(**nov)
```

Lahko pa tudi kombinirata oba pristopa:
```python
class Odpadek(Tabela):
    ...

    def uvozi(self, sez_podatkov):
        imena = {'povzrocitelj': 'pov',
                 'opomba_uvoz': 'op_uv',
                 'skladisce': 'skl',
                 'datum_uvoza': 'dat_uv',
                 'datum_izvoza': 'dat_iz',
                 'opomba_izvoza': 'op_iz'}
        for (kl, teza), slo in sez_podatkov.items():
            self.dodaj_vrstico(klasifikacijska_stevilka=kl, teza=teza,
                               **{stolpec: slo.get(kljuc) for stolpec, kljuc in imena.items()})
```

Še to: na repozitorij se vama je izmuznila mapa `__pycache__`, ki pa tja ne sodi, saj gre za avtomatsko generirane datoteke. Mapo torej pobrišita, v `.gitignore` pa dodajta ustrezno vrstico, da je git ne bo več ponujal za vključevanje v commit. Najbolje bo, da vzameta kar predlogo za [Python](https://github.com/github/gitignore/blob/master/Python.gitignore) - seveda ohranita trenutno vrstico, kot rečeno v #1.

**Comment by CusinM15** [comment]
Hvala za tako hiter in natančen odgovor, je danes uspelo.
Samo še eno vprašanje: Ker je Ekol.sqlite v git ignore, ali to pomeni, da
če eden od naja spremeni bazo drugi ne vidi sprememb?

Lp Matej Čušin
Vesel božič!

V čet., 24. dec. 2020 10:59 je oseba Janoš Vidali <notifications@github.com>
napisala:

**Comment by jaanos** [comment]
Tako je. Kakršnekoli spremembe na bazi, ki niso posledica uporabe aplikacije, naj bodo zabeležene v funkcijah za ustvarjanje baze in uvoz podatkov ter v samih podatkih. Če torej spremenita shemo baze ali kak detajl uvoza, naj se ustvarjanje baze izvede na novo - lokalno bazo torej pobrišeta, potem pa poženeta aplikacijo, ki naj ugotovi, da baze nima, in jo v tem primeru ustvari na novo. Tako naj se postavi baza, potrebna za delovanje aplikacije - ta bo v končni fazi morala delovati neodvisno od vsebine baze (tj., lahko predpostavlja, katere stolpce/omejitve imajo tabele, ne pa tudi, katere vrstice so v njih).

Mimogrede, če sta razrešila problem, opisan v issueju, ga lahko zapreta s klikom na *Close issue* oziroma *Close with comment*, če ob tem še kaj napišeta.

**Comment by CusinM15** [comment]
najlepša hvala :) pa ja trajal je, da sm to najdu
