### ISSUE TITLE
spreminjanje naslovne slike

### ISSUE THREAD

**Issue by TPogacar** [CusinM15/baza-Ekol#4]
Poskušam spremeniti naslovno sliko, a mi nikakor ne uspe. Želim jo nastaviti sliko Jamnika, vendar ne najdem, kje se jo spremeni.

Gledala sem v `\static\assets\css\main.css` in sem v razdelku `Banner` popravila `background-image: url("../../images/banner.jpg");` na `background-image: url("../../images/jamnik.jpg");`, a ni bilo nobenega učinka. Nako sem v vseh `css` in `js` datotekah spremenila `banner` -> `jamnik`, a je bil poskus neuspešen. Poskusila sem tudi tako, da sem obstoječo sliko `banner.jpg` zbrisala ter `jamnik.jpg` preimenovala vanj. A tudi ta poskus je bil neuspešen.

Morda veste, kje bi lahko uspešno spremenila ozadje? Gre se izključno za sliko na vrhu strani.

**Comment by jaanos** [comment]
Kolikor vidim, je slika nastavljena v razdelku `#heading`. Slike `jamnik.jpg` sicer ni na repozitoriju, a deluje, če spremenim v kaj drugega, npr. `kranj.jpg`.

**Comment by TPogacar** [comment]
Hvala. Očitno sem morala samo pobrisati cookije.
