### ISSUE TITLE
#5 težave v html

### ISSUE THREAD

**Issue by CusinM15** [CusinM15/baza-Ekol#5]
# 5 [https://github.com/CusinM15/baza-Ekol/blob/main/views/izpis.html](url) ko poganjava spletni umesnik dobivava napako v vrstici 47. Pred tem sva imela napako v vrstici 36 saj sva "imena" stolpcev vnašala z zanko, ko pa sva spremenila v 
`<tr>
  <th>'Klasifikacijska številka'</th>
  <th>'Naziv'</th> 
  <th>'Število'</th>
</tr>`
pa tu ne javla napake in naju zanima kaj delava narobe pri uporabi for zanke v html.
lp Matej Čušin

**Comment by jaanos** [comment]
Nisem uspel preizkusiti, ampak sumim, da je težava tukaj:
https://github.com/CusinM15/baza-Ekol/blob/6bee825d636d0c6756b85e02573127c8d1713fd5/views/izpis.html#L23-L25
`% end` uporabita za konec Pythonovega zamaknjenega bloka - torej za končanje `if`/`elif`/`else`, `for`, `while`, itd. `import` ne uvede zamaknjenega bloka, zato je uporaba `% end` tukaj neustrezna in povzroči, da sledeča koda pade iz glavnega bloka, tako da pride do napake. Sama zanka `for` mi sicer izgleda v redu.

Še to: pri pisanju na GitHub-u imata možnost *Preview*, s katero lahko preverita, kako bo objava izgledala.

**Comment by jaanos** [comment]
Še ena stvar: besedila v HTML se ne piše v navednicah (tj., med značkami - atribute značk se seveda postavi v navednice).

**Comment by CusinM15** [comment]
....
