### ISSUE TITLE
Nevarne in neučinkovite poizvedbe

### ISSUE THREAD

**Issue by jaanos** [CusinM15/baza-Ekol#6]
Na nekaj mestih v `model.py` vstavljata podatke v poizvedbe s f-stringi - podobno kot v #1 lahko to vodi do napadov SQL injection. Primer takega početja je tukaj:
https://github.com/CusinM15/baza-Ekol/blob/4fbf554de3cb11d6846acdaecba290a24055b641/model.py#L193-L195
Poleg tega se lotita preverjanja veljavnosti skladišča na neučinkovit način, saj iz baze potegneta celoten seznam ID-jev in potem svoj ID poiščeta v njem. Bolje bo tako:
```python
    kje = 'TRUE'
    podatki = []
    if conn.execute("SELECT id FROM skladisce WHERE id = ?", [skladisce]).fetchone():
        kje = 'skladisce = ?'
        podatki.append(skladisce)
```
Poizvedbo seveda potem poženita s `conn.execute(sql, podatki)`. Podobno naredita tudi v metodi `nekateri`.

Nevarno poizvedbo gradita tudi tukaj:
https://github.com/CusinM15/baza-Ekol/blob/4fbf554de3cb11d6846acdaecba290a24055b641/model.py#L416-L430
Glede na to, da tukaj večkrat vnašata isti podatek, bo te bolje podati s slovarjem, npr.
```python
        podatki = {}
        if od is not None or do is not None:
            ...
            poizvedba += """
                 (date(odpadek.datum_uvoza) BETWEEN date(:od) AND date(:do)) OR
                 (date(odpadek.datum_izvoza) BETWEEN date(:od) AND date(:do)) OR
                 ((date(:od) >= date(odpadek.datum_uvoza)) AND
                     ((date(odpadek.datum_izvoza) >= date(:od)) OR (date(odpadek.datum_izvoza) IS NULL)))
            """
            podatki['od'] = od
            podatki['do'] = do
```
Poizvedbo seveda spet kličita s `conn.execute(poizvedba, podatki)`.

**Comment by TPogacar** [comment]
Tisto s `kje = True` je bil sicer le poskus, tako da sem že popravila. Tukaj sicer nikjer ne more priti do `SQL injection`, ker v samem vmesniku nikjer ne dopuščava proste izbire - torej uporabnik nikjer (razen pri vpisu klas. št.,  povzročitelja in prejemnika) ne more vpisati ničesar - lahko zgolj izbira iz danega nabora. Število skladišč ja tako majhno (trenutno 2), da se mi ne zdi problem pregledati vse indexe? Prav tako ne razumem, kako bi si lahko pomagala s tistim, kar ste predlagali.

Prav tako ne razumem, kje je problem pri zapisu časa - `od` in `do` sta vselej ustrezne oblike. Torej bodisi `None` bodisi `yyyy-mm-dd`, torej prav tako ne more priti do `SQL injection`. Prav tako ne razumem, kako bi lahko predlog `date(:do)` ustrezno deloval za `do == None`. Saj kolikor sem poskusila, `date(None)` proži napako.

**Comment by jaanos** [comment]
Če vmesnik ne dopušča poljubnega vnosa, to še ne pomeni, da uporabnik ne more zaobiti vmesnika in strežniku poslati svojih podatkov. Navsezadnje pa je najbolje, da morebiten SQL injection preprečita na mestu, kjer se lahko zgodi - tudi, če ga trenutno že pred tem preprečita, bosta morda v prihodnosti kaj spreminjala in s tem pomotoma odprla to možnost.

Podobno velja s preverjanjem ID-jev skladišč: zdaj mogoče to ni problem, lahko pa se pojavi v prihodnosti.

Kar se tiče `od` in `do`, že sama poskrbita, da nista `None` (kode nisem ponavljal - zato `...`). Tudi, če trenutno vesta, da sta prave oblike, pa ju bo glede na zgoraj napisano bolje vstaviti na varen način.

**Comment by CusinM15** [comment]
pozabla zapret
