### ISSUE TITLE
#7 shranitev tabele v PDF

### ISSUE THREAD

**Issue by CusinM15** [CusinM15/baza-Ekol#7]
Želiva vmesnik tako dopolniti, da bo dal možnost za downloadanje PDF datoteke tabele. Po več youtube posnetkih mi je na tak način izgledalo tako kot želiva, tako da je gumb [https://github.com/CusinM15/baza-Ekol/blob/main/views/izpis.tpl](url) v vrstici 5 in tabelo sem poimenoval, da se lahko nanjo skličeva. Potem pa je v posnetku kodo za ustvarjanje pdf datoteke dal na konec body-a, tako da je ta del v [https://github.com/CusinM15/baza-Ekol/blob/main/views/osnova.tpl](url) (78-89 vrstice) toda nama to nič ne dela (razen, da ustvari neaktiven gumb), tako da bi prosila za pomoč pri tej "nalogi".

**Comment by jaanos** [comment]
Pomemben je vrstni red uvoza knjižnic, prav tako bo potrebno namesto `pdfmake` uporabiti `autotable`. Kombinacija, ki pri meni deluje, je sledeča:
```html
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://rawcdn.githack.com/FuriosoJack/TableHTMLExport/v2.0.0/src/tableHTMLExport.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.13/jspdf.plugin.autotable.min.js"></script>
```

**Comment by CusinM15** [comment]
Hvala za odgovor, deluje.
lp
